### PR TITLE
FDIS-10: Release 1.4.1 with Vert.x 4.1.4

### PR DESCRIPTION
**Pull request by julianladisch**

### CODE REVIEW

**Review by psmagin — COMMENTED** [review]
What about changing the version to 1.4.1 in pom?

**Comment by natali-zaitseva** [comment]
@julianladisch could you follow the steps from the guide, please - https://dev.folio.org/guidelines/release-procedures. Seems that  tag was not published - https://jenkins-aws.indexdata.com/job/folio-org/job/folio-di-support/view/tags/

**Comment by julianladisch** [comment]
> Seems that tag was not published

Yes, I don't push the tag until the release pull request has passed the review, is approved and merged.

Maven created the tag v1.4.1 on commit baf1e5f1417c7dacd9b83e35eac3252c1f64a980 on my local repository.

**Review by adamdickmeiss — APPROVED** [review]

**Comment by julianladisch** [comment]
@natali-zaitseva What else do I need to fix to get PR approval from Spitfire team?

**Review by steveellis — APPROVED** [review]

**Pull request merged**
